name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - run: cd server && npm install && cd ..
      - run: cd client && npm install && npm run build && cd ..
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "turbo-sniffle" #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}